steps:
- name: maven:3-jdk-11
  entrypoint: mvn
  args: ["package", "-Dmaven.test.skip=true"]
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/${_PROJECT}/${_CONTAINERNAME}:${BUILD_ID}","-t", "gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_K8S_NAMESPACE}-latest", "."]
- name: gcr.io/cloud-builders/docker
  args: ["push","gcr.io/${_PROJECT}/${_CONTAINERNAME}"]

# container
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_DEPLOYMENTNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${BUILD_ID}'
  - '--namespace=${_K8S_NAMESPACE}'

  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

  
substitutions:
  _VERSION: v1.0

options:
  substitution_option: 'ALLOW_LOOSE'